services:
  # Solo el panel en Docker
  panel:
    build:
      context: ../TCGT-QA-Panel
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
